### ISSUE TITLE
uninitialized constant ActiveRecordQueryTrace (NameError)

### ISSUE THREAD

**Issue by fifiteen82726** [ruckus/active-record-query-trace#23]
The awesome console is fine when I use `rails s`, but fails in `rspec`.

I put this code in `config/initializers/active_record_query_trace.rb`

```rb
if ENV['QUERY_TRACE'] == 'true'
  ActiveRecordQueryTrace.enabled = true
  ActiveRecordQueryTrace.colorize = 'light purple'
end
```

When I run `rspec`, it threw this error.

```rb
/config/initializers/active_record_query_trace.rb:2:in `<top (required)>': uninitialized constant ActiveRecordQueryTrace (NameError)
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
  from /Users/Coda/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
  from /Users/Coda/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
  from /Users/Coda/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
  from /Users/Coda/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
  from /Users/Coda/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
  from /Users/Coda/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
  from /Users/Coda/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/tsort.rb:411:in `call'
  from /Users/Coda/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
  from /Users/Coda/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
  from /Users/Coda/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/tsort.rb:411:in `call'
  from /Users/Coda/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
  from /Users/Coda/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
  from /Users/Coda/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/tsort.rb:345:in `each'
  from /Users/Coda/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/tsort.rb:345:in `call'
  from /Users/Coda/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
  from /Users/Coda/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
  from /Users/Coda/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
  from /Users/Coda/Desktop/my_project/config/environment.rb:5:in `<top (required)>'
  from /Users/Coda/Desktop/my_project/spec/rails_helper.rb:4:in `require'
  from /Users/Coda/Desktop/my_project/spec/rails_helper.rb:4:in `<top (required)>'
  from /Users/Coda/Desktop/my_project/spec/api/missions_controller_spec.rb:2:in `require'
  from /Users/Coda/Desktop/my_project/spec/api/missions_controller_spec.rb:2:in `<top (required)>'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/bin/rspec:23:in `load'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/bin/rspec:23:in `<main>'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/bin/ruby_executable_hooks:15:in `eval'
  from /Users/Coda/.rvm/gems/ruby-2.1.10@rails320/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by syndbg** [comment]
@fifiteen82726 Did you follow

```
In Rails, add it to your Gemfile, then restart the server:

gem 'active_record_query_trace'
``` ?

If possible provide us the contents of `Gemfile`.

**Comment by fifiteen82726** [comment]
Thanks, It works. 
Another solution

```rb
if ActiveRecord::Type::Boolean.new.type_cast_from_database(ENV['QUERY_TRACE']) && defined?(ActiveRecordQueryTrace)
  ActiveRecordQueryTrace.enabled = true
  ActiveRecordQueryTrace.colorize = 'light purple'
end
```
